/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgnew.lanka.hospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HASITHA
 */
public class Patient extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement Pst = null;
    ResultSet Rs = null;
    Statement st = null;

    /**
     * Creates new form Patient
     */
    public Patient() {
        initComponents();
        showPatient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void showPatient(){
      try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/new lanka hospital", "Hasitha", "1234");
            st = conn.createStatement();
            Rs = st.executeQuery("SELECT * FROM patient");
            patientTable.setModel(DbUtils.resultSetToTableModel(Rs));
        } catch (Exception e) {
        }  
    }
    
    private void Search(){
            try {
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/new lanka hospital", "Hasitha", "1234");
                st = conn.createStatement();
                Rs = st.executeQuery("SELECT * FROM patient WHERE Name LIKE '"+searchTB.getText()+"%'");
                patientTable.setModel(DbUtils.resultSetToTableModel(Rs));
            } catch (Exception e) {
            }
    }
    
    int PatientId;
    
    private void countPatient(){
        try {
            
            st = conn.createStatement();
            Rs = st.executeQuery("SELECT MAX(ID) FROM patient");
            Rs.next();
            PatientId = Rs.getInt(1)+1;
            
        } catch (Exception e) {
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();
        searchTB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PatientName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PatientAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PatientContact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PatientPaymentCB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(34, 87, 122));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "Contact Number", "Payment Type", "Date & Time"
            }
        ));
        patientTable.setPreferredSize(new java.awt.Dimension(500, 500));
        patientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(patientTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 650, 510));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        Refresh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
        });
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 70, -1, -1));

        searchTB.setBackground(new java.awt.Color(56, 163, 165));
        searchTB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchTB.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                searchTBCaretUpdate(evt);
            }
        });
        searchTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTBActionPerformed(evt);
            }
        });
        jPanel1.add(searchTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\Second Year\\Assignment 2nd year\\JAVA\\P. G. Hasitha Dilshan (66933)\\New Lanka Hospital\\IMG\\Dashboard 2.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 0, -1, 770));

        jPanel2.setBackground(new java.awt.Color(56, 163, 165));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));

        PatientName.setBackground(new java.awt.Color(56, 163, 165));
        PatientName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Patient Name");

        PatientAddress.setBackground(new java.awt.Color(56, 163, 165));
        PatientAddress.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Address");

        PatientContact.setBackground(new java.awt.Color(56, 163, 165));
        PatientContact.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Contact Number");

        PatientPaymentCB.setBackground(new java.awt.Color(56, 163, 165));
        PatientPaymentCB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PatientPaymentCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monthly", "Daily" }));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Payment Type");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Previous");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        Add.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Add.setText("Add");
        Add.setPreferredSize(new java.awt.Dimension(93, 28));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Update.setText("Update");
        Update.setPreferredSize(new java.awt.Dimension(93, 28));
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.setPreferredSize(new java.awt.Dimension(93, 28));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PatientContact)
                                    .addComponent(PatientAddress)
                                    .addComponent(PatientName)
                                    .addComponent(PatientPaymentCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(49, 49, 49))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(PatientContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientPaymentCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 150, -1, 500));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        // TODO add your handling code here:

        if(PatientName.getText().isEmpty() || PatientAddress.getText().isEmpty() || PatientContact.getText().isEmpty() || PatientPaymentCB.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Missing Data!!!");
        }else{
            try {
                countPatient();
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/new lanka hospital", "Hasitha", "1234");
                PreparedStatement save = conn.prepareStatement("INSERT INTO `patient` (`Name`, `Address`, `Contact`, `Paytype`) VALUES (?, ?, ?, ?);");

                save.setInt(1, PatientId);
                save.setString(1, PatientName.getText().toString());
                save.setString(2, PatientAddress.getText().toString());
                save.setString(3, PatientContact.getText().toString());
                save.setString(4, PatientPaymentCB.getSelectedItem().toString());

                int row = save.executeUpdate();
                JOptionPane.showMessageDialog(this, "Patient Add !!!");
                conn.close();
                showPatient();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }

    }//GEN-LAST:event_AddMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    int key = 0;
    
    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        // TODO add your handling code here:
        
        if(PatientName.getText().isEmpty() || PatientAddress.getText().isEmpty() || PatientContact.getText().isEmpty() || PatientPaymentCB.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Missing Data!!!");
        }else{
            try {
                countPatient();
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/new lanka hospital", "Hasitha", "1234");
                PreparedStatement save = conn.prepareStatement("UPDATE patient SET Name = ?, Address = ?, Contact = ?, Paytype = ? WHERE ID = ?"); 
                
                save.setInt(5, key);
                save.setString(1, PatientName.getText().toString());
                save.setString(2, PatientAddress.getText().toString());
                save.setString(3, PatientContact.getText().toString());
                save.setString(4, PatientPaymentCB.getSelectedItem().toString());
              
                int row = save.executeUpdate();
                JOptionPane.showMessageDialog(this, "Patient details update !!!");
                conn.close();
                showPatient();
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
        
    }//GEN-LAST:event_UpdateMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        // TODO add your handling code here:
        
        if(key == 0)
        {
            JOptionPane.showMessageDialog(this, "Select a Patient");
        }else{
            try {
                
                conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/new lanka hospital", "Hasitha", "1234");
                PreparedStatement save = conn.prepareStatement("DELETE FROM patient WHERE ID = ?"); 
                
                save.setInt(1, key);
              
                int row = save.executeUpdate();
                JOptionPane.showMessageDialog(this, "Patient Deleted !!!");
                conn.close();
                showPatient();
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
        
    }//GEN-LAST:event_DeleteMouseClicked

    private void patientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientTableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        int Patient = patientTable.getSelectedRow();
        key = Integer.valueOf(model.getValueAt(Patient, 0).toString());
        PatientName.setText(model.getValueAt(Patient, 1).toString());
        PatientAddress.setText(model.getValueAt(Patient, 2).toString());
        PatientContact.setText(model.getValueAt(Patient, 3).toString());
        PatientPaymentCB.setSelectedItem(model.getValueAt(Patient, 4).toString());
        
    }//GEN-LAST:event_patientTableMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshMouseClicked

    private void searchTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTBActionPerformed

    private void searchTBCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchTBCaretUpdate
        // TODO add your handling code here:
        Search();
    }//GEN-LAST:event_searchTBCaretUpdate

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        showPatient();
        searchTB.setText("");
    }//GEN-LAST:event_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField PatientAddress;
    private javax.swing.JTextField PatientContact;
    private javax.swing.JTextField PatientName;
    private javax.swing.JComboBox<String> PatientPaymentCB;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable patientTable;
    private javax.swing.JTextField searchTB;
    // End of variables declaration//GEN-END:variables
}
